### ISSUE TITLE
Trailing slash on Swagger link

### ISSUE THREAD

**Issue by ccondit** [SciGraph/SciGraph#104]
http://localhost:9000/scigraph/docs/ resolves
but http://localhost:9000/scigraph/docs does not. Should resolve to the same spot.

**Comment by tgbugs** [comment]
I am still seeing this bug at 06acce3d8a185ede2797ef76b2a64bc24eb657d6 after a full rebuild.

**Comment by ccondit** [comment]
Are you using matrix?
http://matrix.neuinfo.org:9000/scigraph/docs

**Comment by tgbugs** [comment]
Matrix is fine, but when I rebuild on kaa.neuinfo.org I still have the old behavior. Is there some way to force maven to do a clean build (I was under the impression that it was always a clean rebuild)?

**Comment by ccondit** [comment]
I'm not sure what that host is. Is there a bamboo job for it?
maven should manage all of that for you but you could always run `mvn clean package`.

**Comment by tgbugs** [comment]
It is the development host I'm using for the methods ontology, there is no bamboo job I'm just following github readme at the moment (since I need to provide something that the incf/hbp folks can follow).
