### ISSUE TITLE
Graph or ontology-level properties mapped into SciGraph

### ISSUE THREAD

**Issue by cmungall** [SciGraph/SciGraph#106]
SciGraph loads individual ttl or owl documents. On the RDF level each is considered a distinct *named graph*. On the OWL level each is it's own distinct *ontology* (which is confusing terminology as these may purely be data).

Each such set may have its own properties: e.g. HPO annotations may have a link of dc:source to the HPO website.

At the moment I believe this gets lost as neo4j doesn't have a direct cognate of a named graph. We would have to explicitly model this.

Each distinct document loaded should have it's own node S (with various properties associated - this is in a separate file for us). Then we can add a property linking an edge E to S, if E came from the document associated with S (we can't have true hyperedges in Neo4j so this would be a reference in the form of a shared CURIE)

**Comment by ccondit** [comment]
In this case does S correspond to the `OWLOntologyID` for the ontology document?

**Comment by cmungall** [comment]
Yes. We may need to review the dipper code to ensure every dataset has this set

**Comment by ccondit** [comment]
@cmungall -
Should this apply to all axioms in an ontology / named graph (or just object properties)?
Should declaration axioms also be linked to S or just relationships?

**Comment by ccondit** [comment]
Should this happen pre or post reasoning?

**Comment by cmungall** [comment]
post
