### ISSUE TITLE
return CURIES in annotate service

### ISSUE THREAD

**Issue by cmungall** [SciGraph/SciGraph#108]
Example:

http://geoffrey.crbs.ucsd.edu:9000/scigraph/annotations/entities.json?content=SHH+neuonitis+neurons+development+lung&minLength=4&longestOnly=false&includeAbbrev=false&includeAcronym=false&includeNumbers=false

Currently URIs are in the id field. Can we have it so that the keys in the json object are consistent with other parts of the SG API? E.g. fragment, id, CURIE, uri

**Comment by ccondit** [comment]
Should all of those properties be included? 
Or should id be a CURIE if mapped, otherwise an IRI?
