### ISSUE TITLE
Load CURIE mapping for NIFSTD

### ISSUE THREAD

**Issue by twhetzel** [SciGraph/SciGraph#112]
@ccondit  Can you load this file for NIFSTD http://ontology.neuinfo.org/NIF/nifstd_curie_map.txt in SciGraph?

**Comment by cmungall** [comment]
I recommend managing this in github, as a yaml file (very easy to cvt your existing file)

**Comment by tgbugs** [comment]
Is there an existing repo we can put it in or should we just create a new one for nifstd related things?

**Comment by twhetzel** [comment]
Currently all NIFSTD files are in a UCSD SVN repo. Previously we decided to
not move the files to GitHub due to space constraints.

**Comment by tgbugs** [comment]
Without knowing more of the history behind this can I just bug someone to set us up a git server? Alternately I can create a public repo under this account since I'm a student. If we need to transition later it is trivial to set up our own git server (I'm surprised we don't have one already).

**Comment by twhetzel** [comment]
If there isn't a requirement that the CURIE file exist in GitHub then
there's no need to complicate this task of testing CURIEs with
re-organizing the NIFSTD repo.

**Comment by tgbugs** [comment]
No issues here.

**Comment by tgbugs** [comment]
@ccondit the yaml file is located here: http://ontology.neuinfo.org/NIF/nifstd_curie_map.yaml, can you load it directly from there for now or do you want it in a git repo somewhere?

**Comment by ccondit** [comment]
@tgbugs the CURIE configuration is ambiguous:

    Multiple entries with same value: NIFSTD=http://uri.neuinfo.org/nif/nifstd/ and =http://uri.neuinfo.org/nif/nifstd/

Can you modify accordingly?

**Comment by tgbugs** [comment]
@ccondit yep will do, getting access from Larry as we speak. I'll ping again when its done.

**Comment by cmungall** [comment]
If this were in github I'd make you a pull request...

I believe the various NIFSTD ones require a hash at the end? If we are indeed keeping them...

@twhetzel , I thought we were going for a uniform prefix that maps everything in the old NIFSTD to `ttp://uri.neuinfo.org/nif/nifstd/`?

**Comment by twhetzel** [comment]
@tgbugs if you have updates to the file to post, I can add the updated file to the server in the meantime

**Comment by tgbugs** [comment]
@twhetzel go ahead, I'm fighting with ssh at the moment, thanks

**Comment by twhetzel** [comment]
@tgbugs Do you have an updated file?

**Comment by tgbugs** [comment]
@twhetzel @ccondit updated version is there now (finally got access), I also fixed the #s on the old NIFSTD entries.

**Comment by ccondit** [comment]
Ok - this is deployed. If you need to update again all you need to do it run this build:
https://bamboo.crbs.ucsd.edu/browse/NIF-NIFSCIWS
No need to file a ticket here.
