### ISSUE TITLE
dynamic gene queries not working

### ISSUE THREAD

**Issue by nlwashington** [SciGraph/SciGraph#114]
on both duckworth and rosie, gene queries don't seem to be working.  true for:
<pre>
http://duckworth.crbs.ucsd.edu:9000/scigraph/dynamic/phenotypes/phenotype_id/genes
http://duckworth.crbs.ucsd.edu:9000/scigraph/dynamic/genes/gene_id/phenotypes
</pre>
for example, if i query with HP:0100750, i get nothing:
http://duckworth.crbs.ucsd.edu:9000/scigraph/dynamic/phenotypes/HP:0100750/genes

but, if i look for features, they are there:
http://duckworth.crbs.ucsd.edu:9000/scigraph/dynamic/phenotypes/HP:0100750/features

i get back a bunch of stuff.  this includes:
<pre>
   {"id": "_:genid1201505",
    "lbl": "Lox<tm1Soin>/Lox<tm1Soin>",
    "meta": 
        {"category": [ ] } },
</pre>
but it doesn't include the inference to the gene!  (the Lox gene is not included in the list.)
this ought to be linked to the gene Lox (MGI:96817) via the variant locus Lox<tm1Soin> (MGI:3610732).  We can see that 
```_:genid1201505  --[BFO:0000051]-->  MGI:3610732 --[GENO:0000408]--> MGI:96817```

so what's going on here?

**Comment by ccondit** [comment]
@nlwashington - This call returns genes now. Are they correct?
