### ISSUE TITLE
summary cypher queries

### ISSUE THREAD

**Issue by nlwashington** [SciGraph/SciGraph#115]
we want a service that will do things like:

"get me all the unique nodes of type Y with a filter of Z"

this could be accomplished in two ways:
1.  query by a category and getting back a list.  (a new service)
2.  a graph cypher query that goes via relationshipType=type or relationshipType=subClassOf

while (2) works, it will be painfully slow if you queried by a root node of an ontology (say, DOID:4), and wanted to get a flat list of all of it's instances or children.  

what would be the best way of going about this?  example queries might be:
* get all disease ids (basically, all children of DOID:4)
* get all genotypes (all instances of GENO:0000000)

and/or perhaps this is better to go about via Golr?

**Comment by ccondit** [comment]
Could this be solved by allowing the client to control the projection on the `/graph` resource?

**Comment by ccondit** [comment]
In combination with the implemented CSV format and the new projection option it should be easy to produce these things with:
scigraph/graph/neighbors/DOID:4.csv?project=curie&relationshipType=subClassOf&direction=INCOMING&depth=10000
or
scigraph/graph/neighbors/GENO:0000000.csv?project=curie&relationshipType=type&direction=INCOMING&depth=10000
