### ISSUE TITLE
Stalled SciGraph queries

### ISSUE THREAD

**Issue by bryanlaraway** [SciGraph/SciGraph#117]
Running into an issue with certain 'phenotypes for a disease' REST queries stalling. This query for OMIM:600155 (HIRSCHSPRUNG DISEASE, SUSCEPTIBILITY TO, 2; HSCR2) takes a few minutes to complete:
http://rosie.crbs.ucsd.edu:9000/scigraph/dynamic/diseases/OMIM:600155/phenotypes/targets.json
This one for OMIM:607373 (AUTISM, SUSCEPTIBILITY TO, 8; AUTS8) still hasn't completed after five minutes:
http://rosie.crbs.ucsd.edu:9000/scigraph/dynamic/diseases/OMIM:160990/phenotypes/targets.json

Not sure if this might be an issue with the query returning a large number of associated phenotypes, but then again on the Monarch website OMIM:607373 only returns 12 phenotypes: http://monarchinitiative.org/disease/OMIM:607373
OMIM:600155 only returns one phenotype.
http://monarchinitiative.org/disease/OMIM:600155

**Comment by bryanlaraway** [comment]
Here's a list of OMIM IDs that are not returning phenotypes in 10 seconds or less:
OMIM:612702
OMIM:608995
OMIM:157300
OMIM:600155
OMIM:240500
OMIM:224690
OMIM:613494
OMIM:607373
OMIM:308700
OMIM:607498
OMIM:143465
OMIM:600669
OMIM:600156
OMIM:607628
OMIM:613800
OMIM:607594
OMIM:271322
OMIM:607508
OMIM:610628
OMIM:177900
OMIM:181500
OMIM:137800
OMIM:613805
OMIM:244200
OMIM:613496
OMIM:114500
OMIM:613804
OMIM:102300
OMIM:613493
OMIM:607850
OMIM:127700
OMIM:608636
OMIM:600850
OMIM:612370
OMIM:613495
OMIM:612591
OMIM:608762
OMIM:142623
OMIM:612229
OMIM:607516
OMIM:181510
OMIM:606053
OMIM:147950
OMIM:608049
OMIM:130100
OMIM:600202
OMIM:607682
OMIM:613803
OMIM:600511

**Comment by ccondit** [comment]
Resolved. Now not including all parent phenotypes.
