### ISSUE TITLE
SciGraph 'Get genes related to a phenotype' request not returning the correct data

### ISSUE THREAD

**Issue by bryanlaraway** [SciGraph/SciGraph#120]
I noticed that the 'genes for a phenotype' query isn't returning the expected data. For example, for HP:0000878 (11 pairs of ribs), there should be 8 genes returned via OMIM/HPO (ATR, B3GALT6, HDAC, FLNB, LBR, RNU4ATAC, RPS19, SOX9) according to the data we have in DISCO/NIF. However, the SciGraph query doesn't return any of these genes at the moment.

Here's the request URL:
http://rosie.crbs.ucsd.edu:9000/scigraph/dynamic/phenotypes/HP:0000878/genes/targets

I know that these calls were down for a bit, so perhaps you are still working on the configuration, but I wanted to pass along what I'm seeing as I'm working with querying the services and using the output.

Thanks!

**Comment by kshefchek** [comment]
Getting gene to phenotype associations in the RDF model requires traversing an anonymous node.  @ccondit how are anonymous nodes handled in the Neo4J conversion?  If these are converted to real nodes, we'll just need to add (gene)-[GENO_0000408]-(variant)-[r:RO_0002200*]->(phenotype) to the cypher query (or something along those lines).  In this case, variant is the anonymous node in the RDF model.

**Comment by ccondit** [comment]
This is actually just operating on a stale version of the phenotype->gene query. Will fix after @nlwashington gives the OK to move duckworth data to rosie.

@kshefchek anonymous nodes are loaded by neo4j. This pattern was just missing from the Cypher query.

**Comment by kshefchek** [comment]
@ccondit would it be possible to get the template queries for rosie and duckworth into the configs repo?  I see we have one file there; I'm assuming it's for rosie?

**Comment by ccondit** [comment]
@kshefchek see: monarch-initiative/configs#2

**Comment by ccondit** [comment]
Resolved on duckworth. Will move to rosie as the release approaches.
