### ISSUE TITLE
add search by relationship type

### ISSUE THREAD

**Issue by aguptasd** [SciGraph/SciGraph#122]
Given a relationship type (a URI) or a label, return all edges satisfying the label. If needed, have an extra parameter to return results in batches.

**Comment by cmungall** [comment]
Should there be a parameter to include the property hierarchy or other
property axioms? Ie equivalent of isDirect in owapi reasoner Api?

**Comment by aguptasd** [comment]
For the requirement I was coming from there was no need to include the property hierarchy or other property axioms. However, I do see that it will be useful to have such a parameter.

**Comment by ccondit** [comment]
Does it suffice to have a single parameter that would indicate inclusion of sub / equivalent properties? What should the default be?
