### ISSUE TITLE
Pull in axiom annotations

### ISSUE THREAD

**Issue by Kabenla** [SciGraph/SciGraph#123]
Sci-graph currently ignores owl:axiom annotations in an ontology. It would be nice if we could add axiom annotations to the edges of the graph.

**Comment by cmungall** [comment]
There might be an argument for unifying all forms of edge reification in SG:

 * OWL2 axiom annotations
 * RDF reification
 * Named graphs, quads
 * Other custom annotation schemes and models, including OBAN, but possibly others

Not quite sure how this would work though. We could duplicate the properties of the reified edge node on the edge itself, but that feels inelegant.

Maybe there is no action here, but it's useful to note that there are different reification schemes, and each will result in different SG structures

**Comment by ccondit** [comment]
These class annotation assertions are handled by SciGraph (see the first example here: https://github.com/SciGraph/SciGraph/wiki/Neo4jMapping). We can take @cmungall's comment as a separate ticket when the time comes.
