### ISSUE TITLE
New NIFSTD curie file location and NIFMOL curie not working

### ISSUE THREAD

**Issue by tgbugs** [SciGraph/SciGraph#124]
Here is the new location for the NIFSTD curie yaml file:
https://raw.githubusercontent.com/SciCrunch/NIF-Ontology/master/scigraph/nifstd_curie_map.yaml
(will be made public shortly)

Bug:
curie is defined as
'NIFMOL': 'http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-Molecule.owl#'
but for some reason it is appearing as null in scigraph
http://matrix.neuinfo.org:9000/scigraph/vocabulary/id/nlx_mol_1012006
http://matrix.neuinfo.org:9000/scigraph/vocabulary/id/nlx_mol_20090405

For comparison: 
'NIFORG': 'http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-Organism.owl#'
http://matrix.neuinfo.org:9000/scigraph/vocabulary/id/nlx_organ_110506
works with no issues.

**Comment by ccondit** [comment]
CURIES should be unique. That CURIE map has two entries for NIFMOL:
`'NIFMOL': 'http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-Molecule.owl#'`
and
`'NIFMOL': 'http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-Molecule-Role-Bridge.owl#'`

Only the last one gets used.
