### ISSUE TITLE
BatchOwlLoader hangs when loading chebi.owl

### ISSUE THREAD

**Issue by tgbugs** [SciGraph/SciGraph#125]
At commit f42574ef50c831b14b4b0e25910bb5985e4718b3 when I try to load http://purl.obolibrary.org/obo/chebi.owl directly from the site or locally BatchOwlLoader hangs and does not finish loading the file. The config file I'm using is as follows:

        graphConfiguration:
            # The location of the graph.
            # If this location does not exist it will be created.
            # Loading will append content to existing graphs.
            location: /tmp/methodsGraph
            indexedNodeProperties:
              - label
              - fragment
            exactNodeProperties:
              - label
              - fragment
              - definition
              - synonym
              - acronym
              - abbreviation
              - deprecated

        # A list of ontologies to import.
        ontologies:
          - url: http://raw.githubusercontent.com/tgbugs/methodsOntology/master/ttl/nsmethods.ttl
          - url: http://raw.githubusercontent.com/tgbugs/methodsOntology/master/ttl/nsbeing.ttl
          - url: http://purl.obolibrary.org/obo/chebi.owl  # FIXME chokes
            reasonerConfiguration:
              factory: org.semanticweb.elk.owlapi.ElkReasonerFactory

        # All properties are stored but can optionally be added to a new node property
        mappedProperties:
          - name: label # The name of the new property
            properties: # The list of properties mapped to the new property
            - http://www.w3.org/2000/01/rdf-schema#label
          - name: comment
            properties:
            - http://www.w3.org/2000/01/rdf-schema#comment
          - name: definition
            properties:
            - http://www.FIXME.org/nsupper#definition
            - http://purl.obolibrary.org/obo/IAO_0000115
          - name: synonym
            properties:
            - http://www.FIXME.org/nsupper#synonym
            - http://www.geneontology.org/formats/oboInOwl#hasSynonym
            - http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym
            - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
            - http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym
          - name: acronym
            properties:
            - http://www.FIXME.org/nsupper#acronym
          - name: deprecated
            properties:
            - http://www.w3.org/2002/07/owl#deprecated

And the command is `mvn exec:java -Dexec.mainClass="edu.sdsc.scigraph.owlapi.loader.BatchOwlLoader" -Dexec.args="-c config.yaml"`

**Comment by ccondit** [comment]
Are you using the latest from the repo?

**Comment by tgbugs** [comment]
It was done at HEAD~1. If you can't repro it then it is probably something off on my end. I'll look around and see if I can find the issue. Thanks.
