### ISSUE TITLE
graph service direction=in causes internal server error

### ISSUE THREAD

**Issue by tgbugs** [SciGraph/SciGraph#129]
The old settings for the direction option are causing 500 errors.
This fails: http://matrix.neuinfo.org:9000/scigraph/graph/neighbors/UBERON_0000955.json?depth=1&relationshipType=BFO_0000050&blankNodes=false&direction=in
This works: http://matrix.neuinfo.org:9000/scigraph/graph/neighbors/UBERON_0000955.json?depth=1&relationshipType=BFO_0000050&blankNodes=false&direction=INCOMING

**Comment by ccondit** [comment]
`direction=in` is no longer supported. The supported directions are:
`INCOMING`, `OUTGOING`, or `BOTH`

**Comment by tgbugs** [comment]
Sorry, should have added a question. Is throwing a 500 error expected behaviour when a bad value is passed in?

**Comment by ccondit** [comment]
Will add validation.

**Comment by tgbugs** [comment]
Ok, great, thanks!

**Comment by tgbugs** [comment]
As of c817bdf171c4c96eb313224c31d4a1ef21f734e3 it looks like these are now returning 404 errors which I think is expected behavior. The revision that was giving 500 errors was 3ba76f4ba437d3539f736604dc42316910649d6a, looking at the diffs there seems to have been a change to [GraphService.java](https://github.com/SciGraph/SciGraph/tree/master/SciGraph-services/src/main/java/edu/sdsc/scigraph/services/resources/GraphService.java) that might account for the change.

**Comment by ccondit** [comment]
Hmmm. I would think 400 might be a better response.
