### ISSUE TITLE
get all paths that contain a specified node (X...Z...Y)

### ISSUE THREAD

**Issue by nlwashington** [SciGraph/SciGraph#13]
i'd like to specify a query between two items of any path length, that pass through a particular node.

for example.  i'd like to ask...   what are the paths between geneX and geneY that contain geneZ.

furthermore, i'd really like to be able to specify the valid paths that can be followed (by relationship types).

**Comment by ccondit** [comment]
In theory this could be solved with the skyline queries @aguptasd is suggesting.
