### ISSUE TITLE
Remove redundant axioms prior to adding to Neo4j

### ISSUE THREAD

**Issue by cmungall** [SciGraph/SciGraph#130]
We sometimes have situations where an ontology will have asserted axioms

 1. `A SubClassOf B`
 2. `A SubClassOf C`

then due to other axioms in the ontology we have an entailed axiom

 3. `B SubClassOf C`

We populate all entailed direct axioms (see #42) so we end up with edges 1, 2 and 3, but 2 is now redundant, so we would like to remove this axiom prior to loading. This will fix the ZP issue mentioned by @nlwashington.

@hdietze can answer any questions - more formal description of redundancy can be found here:
ontodev/robot#16

(we *could* use robot prior to loading but the functionality is fairly straightforward here so simplest not to introduce a dependency)

**Comment by ccondit** [comment]
owlapi code here: https://goo.gl/NkBC6Q

**Comment by jmcmurry** [comment]
related to https://github.com/monarch-initiative/monarch-app/issues/777
