### ISSUE TITLE
synonyms blacklist/additions

### ISSUE THREAD

**Issue by tgbugs** [SciGraph/SciGraph#131]
Hi Chris,
A feature request. One of the things we have trouble doing right now is managing synonyms for search from imported ontologies (that we don't have control over and where upstream usually isn't responsive on the time scale we need). After talking with @jgrethe it seems like SciGraph is probably the best place to add global (and hopefully per-term) blacklists/additions for synonyms so that it will be possible to make changes for search without having to maintain and synchronize local copies of ontologies we need to 'patch.' Would it be possible to add a section to the yaml file for services and an option on the rest services along the lines of &synonymBlacklist=false by default (and the accompanying backend changes) so that we could blacklist certain synonyms from completions for search?

In the short term a global blacklist would get us 80% of the way to what we need. In the long run the ability to add per-term patches with additions/removals would solve 100% of the issues we have when dealing with imported ontologies but I suspect would take loner to implement.
Thanks!

**Comment by tgbugs** [comment]
One additional note. We should be able to manage additions via bridge files, but we have no way to manage removals, so we probably just need the blacklist functionality, and Maryann noted that in many cases we would probably need programmatic (ie pattern matching) functionality.

**Comment by cmungall** [comment]
What would the OWL representation of a blacklisted synonym look like? You can't do this explicitly (mixing a logical construct like negation with an annotation property), but there is nothing to prevent invention of annotation properties with your own semantics; or this could be an annotation of the existing axiom. E.g.

uberon.owl:
```
AnnotationAssertion(oboInOwl#hasRelatedSynonym UBERON:0000074 "glomerulus")
```

myProject.owl:

```
AnnotationAssertion(Annotation(owl:isDeprecated "true") oboInOwl#hasRelatedSynonym UBERON:0000074 "glomerulus")
```

**Comment by tgbugs** [comment]
That seems like a reasonable construction. Since we can't really hard code something like that into SciGraph I'm guessing the way to implement this kind of solution in production would be to write a custom cypher in the yaml file to replace whatever is being used for synonym expansion right now.

**Comment by cmungall** [comment]
I think you could do something like this in a fairly generic way. Just define a new AP (owl:isDeprecated is probably not a good idea). The AP IRI could be specified in the yaml. I can add an AP to RO for this. E.g. isIgnored=true.

A slight variation on this is that instead of making this boolean, we use an anti-slim (the converse of a slim, as in GO slim). You could specify a URL for an HBP anti-slim, and then annotate axioms with an annotation

    isInSubSet http://foo.org/hbpAntiSlim

**Comment by tgbugs** [comment]
The antislims seem like a better pattern for this. @aguptasd also suggested that we could probably implement blacklists algorithmically with a cypher query that runs post load and adds an annotation property like the one proposed by @cmungall to all terms that match the query. He also mentioned that @ccondit has written other cypher queries that are used post load for monarch, Chris C do you have examples of these that you could point me to (looking around monarch github repos hasn't turned up anything)? Thanks!

**Comment by ccondit** [comment]
There's an example of adding a cypher resource in the "getting started" configuration:
https://github.com/SciGraph/SciGraph/blob/master/SciGraph-services/src/test/resources/pizzaConfiguration.yaml

**Comment by tgbugs** [comment]
Following up, if I want to run a cypher query to add annotation properties but not set it up as a cypherResource is there a place in the yaml file that can do that (there doesn't seem to be one in the example)?

**Comment by ccondit** [comment]
At this point SciGraph is read only (other than the load process). If you want to do this I suggest you load the graph and then run your Cypher query as an out of band process. 

This is a good use case for allowing custom post-processing code.

**Comment by tgbugs** [comment]
Yes, for the time being I can load the graph and then do the query out of band but it would be great to be able to do it all from the graph load yaml file.
