### ISSUE TITLE
Ajax jsonp calls to /graph/neighbors returns different JSON structure

### ISSUE THREAD

**Issue by kshefchek** [SciGraph/SciGraph#134]
When writing an ajax call with the client I am expecting back a JSON blob in the BBOP graph format; however, I'm getting a different JSON structure @ccondit suspects it may be serializing the tinkergraph.

For example:

        {"vertices":[{"id":"78968","propertyKeys":["category","http://zfin/definition/source_information",...

Is it possible to add an option to return a specified format or return the bbop graph format as a default?

**Comment by ccondit** [comment]
Added CORS for now. Look into fixing the default JSONP response or removing the JSONP functionality.

**Comment by kshefchek** [comment]
I am occasionally seeing this error on my client:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/neighbors/HP:0012638.json?depth=1&blankNodes=false&relationshipType=subClassOf&direction=INCOMING&project=*. (Reason: CORS header 'Access-Control-Allow-Origin' does not match 'http://localhost:8080').

It seems to work sometimes and sometimes not.  Could this be an issue with my client or is this related to the cors settings on the scigraph server?

**Comment by ccondit** [comment]
Is it some call in particular or it just happens intermittently?

**Comment by kshefchek** [comment]
I haven't been able to reproduce the issue so it may have been related to being on the OHSU network.  I'll test again on Monday.

**Comment by ccondit** [comment]
Please reopen if this is still an issue.
