### ISSUE TITLE
broken ontology imports

### ISSUE THREAD

**Issue by tgbugs** [SciGraph/SciGraph#136]
New versions of SciGraph now fail to load nif.owl. I have encountered a similar issue with trying to load nif.owl in newer versions of protege using owlapi v4. No remote imports are resolvable by owlapi despite web browsers being able to resolve them.

The change from Ontology -> OntologyIri may be an issue in this commit:
https://github.com/SciGraph/SciGraph/commit/922fac8491e4564a77da32ea1f9daaa63c5b3cdb

Log from matrix build here: https://bamboo.crbs.ucsd.edu/download/NIF-NIFSCIGRAPH-JOB1/build_logs/NIF-NIFSCIGRAPH-JOB1-27.log

**Comment by ccondit** [comment]
Related to work for #106.

This is caused by a circular import in the nif.owl import chain. `NIF-Chemical` imports `NIF-Molecule` which imports `NIF-Investigation` which imports `NIF-Chemical`. There's nothing wrong with this - just that SciGraph didn't handle this input...

**Comment by tgbugs** [comment]
Hrm, thanks. I'll look into whether that is also causing the related issues.

**Comment by ccondit** [comment]
@tgbugs it isn't necessarily a problem to do this - just may not be as manageable as keeping the ontology structure a DAG. SciGraph should handle this correctly now.

**Comment by tgbugs** [comment]
Yep, that fixed it. Thanks!
