### ISSUE TITLE
Create a SciGraph dynamic template to replace GO taxon server

### ISSUE THREAD

**Issue by cmungall** [SciGraph/SciGraph#140]
Input: (speciesTaxonomyClass `T`, anyOntologyClass `C`, RelationSet `R`)
Return: true/false  (true if there is a violation)

This is essentially a path check, or a union of two path checks using 

 * [RO:0002160](http://purl.obolibrary.org/obo/RO_0002160) ! only in taxon
 * [RO:0002161](http://purl.obolibrary.org/obo/RO_0002161) ! never in taxon

Composed with other OPs

Test 1:

Findall paths starting at `C`, traverse up following any edge type in R, followed by exactly 1 RO_0002160 followed by zero or more subClassOfs going up. If `T` is *not* in the resulting path then we have a violation

Test 2:

(declarative specification)

Findall paths starting at `C`, traverse up following any edge type in R, followed by RO_0002161, after this switch direction and traverse down over zero or more subClassOfs. If `T` *is* in the resulting path then we have a violation

(more efficient specification)

Findall reflexive transitive superclasses of `T`, `T* = Ancs(T)`; find all paths starting at `C` following any in `R` followed by exactly 1 RO_0002161. Call the end of this path `Tn`. If `Tn` is a member of `T*` then we have a violation

The most elegant way to implement this would be a dynamic template - it is possible to use two variables, see http://datagraph.monarchinitiative.org/docs/#!/dynamic/get_evidence_for_a_pair_of_ids

We may also want to call this by direct JVM calls too

Note: should be assigned to @hdietze 

Tester: @selewis (in PAINT)

**Comment by selewis** [comment]
Happy to test, but I should also commit the taxon lookup code (for
attempting to determine the correct NCBI taxon id). Not a dependency, but
be good to have both available. Later today I hope.

-S

**Comment by cmungall** [comment]
Note you can also do reconciliation using SG vocab services, e.g. http://geoffrey.crbs.ucsd.edu:9000/scigraph/vocabulary/term/mammals?limit=20&searchSynonyms=true&searchAbbreviations=false&searchAcronyms=false

**Comment by ccondit** [comment]
Per @cmungall can test with:
http://geneontology.org/page/download-ontology#go-plus.owl

**Comment by jnguyenx** [comment]
@cmungall Can you provide several test cases with concrete IRIs please?

**Comment by cmungall** [comment]
```
Prefix: : <http://scigraph.io/>
Prefix: RO: <http://purl.obolibrary.org/obo/RO_>
Prefix: only_in_taxon: <http://purl.obolibrary.org/obo/RO_0002160>
Prefix: never_in_taxon: <http://purl.obolibrary.org/obo/RO_0002161>
Prefix: part_of: <http://purl.obolibrary.org/obo/BFO_0000050>

## Taxon test 
Ontology: <http://scigraph.io/test.owl>

ObjectProperty: never_in_taxon:
ObjectProperty: only_in_taxon:
ObjectProperty: part_of:

## Taxonomy

Class: :animal
Class: :vertebrate SubClassOf: :animal
Class: :mammal SubClassOf: :vertebrate
Class: :mouse SubClassOf: :mammal
Class: :human SubClassOf: :mammal
Class: :bird SubClassOf: :vertebrate
Class: :chicken SubClassOf: :bird

## Ontology with taxon constraints

Class: :hair
  SubClassOf: only_in_taxon: some :mammal
Class: :whisker SubClassOf: :hair
  SubClassOf: never_in_taxon: some :human
Class: :tip_of_whisker SubClassOf: part_of: some :hair
Class: :hair_root SubClassOf: part_of: some :hair

## EXPECTED:
## R = [SubClassOf, part_of]
## 
## violation(whisker, human) = true
## violation(whisker, mammal) = false
## violation(whisker, vertebrate) = false
## violation(whisker, chicken) = true
## violation(tip_of_whisker, human) = true
## violation(tip_of_whisker, mammal) = false
## violation(tip_of_whisker, mouse) = false
## violation(hair, chicken) = true
## violation(hair_root, chicken) = true
## violation(hair, bird) = true
## violation(hair_root, bird) = true
## violation(hair, vertebrate) = false
## violation(hair_root, vertebrate) = false
```

**Comment by jnguyenx** [comment]
Implemented and added to the Monarch instance in the meantime.

Next is to deploy a GO SciGraph instance.
