### ISSUE TITLE
Robustifying multi-import loads

### ISSUE THREAD

**Issue by cmungall** [SciGraph/SciGraph#141]
there is always a non-zero probability that an ontology IRI will not resolve. The loader may want to have strategies for retrying, cacheing etc - but it should always fail fast.

Can you assign to @hdietze to do a code review to verify existing loader?

cc @nlwashington

**Comment by ccondit** [comment]
Still not quit working. See latest build:
https://bamboo.crbs.ucsd.edu/download/MON-SAGL2-JOB1/build_logs/MON-SAGL2-JOB1-71.log

**Comment by jnguyenx** [comment]
At the moment we use the [ExecutorService#shutdownNow()](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ExecutorService.html#shutdownNow()) which works on best effort and doesn't guarantee an immediate interruption of the Threads. But the load will eventually fail on an error.

For an immediate failure we'll need to come up with our own solution, for example polling from each Thread to check if an interrupt has been thrown. For now I'd like to avoid this boilerplate code and close this issue. Feel free to reopen it if the need of haven't an immediate failure for a load is present.
