### ISSUE TITLE
Add service call for introspection of load state

### ISSUE THREAD

**Issue by cmungall** [SciGraph/SciGraph#142]
We would like the monarch site to be able to say "service unavailable" if the data is loading, this would require the ability to introspect SG and/or Golr to say "are you ready" with the ability to return with "loading"

@kltm is this something me have in golr already?

**Comment by kltm** [comment]
GOlr itself is just the standard Solr and quite dump--this is actually accomplished with the help of AmiGO (although not used in production for some reason that I forget).

If the balancing configuration is on and it's not getting a proper response, it will give an error page.

As well, Jenkins jobs are able to create error flags/messages using bundled scripts that allow AmiGO to display various custom warn-off messages in cases like loading: http://wiki.geneontology.org/index.php/AmiGO_2_Manual:_Administration#System_messages_and_global-message.pl

The widgets themselves can catch a wide variety of errors and trigger events for them, but it's probably best to have it happen at the monarch-app level.
