### ISSUE TITLE
Add CURIE support in SciGraph configuration file

### ISSUE THREAD

**Issue by jnguyenx** [SciGraph/SciGraph#147]

**Comment by tgbugs** [comment]
Pretty sure CURIEs are supported in the web services config file, see here: 
https://github.com/SciGraph/SciGraph/blob/master/SciGraph-services/configuration.yml#L73

**Comment by ccondit** [comment]
This ticket is about allowing CURIEs in the configuration file for categories and mapped properties.

**Comment by ccondit** [comment]
Let's raise an exception if the configuration uses a CURIE that doesn't exist in the configuration.

**Comment by jnguyenx** [comment]
I didn't find a way to identify a string as an IRI or CURIE. The IRI rfc does not say explicitly that an IRI has to start with `http`. The best we can do is what we have right now in my opinion, try to expand a potential CURIE and leave it as is when no conversion is found.

**Comment by jnguyenx** [comment]
You can't have forward slashes in curies?
