### ISSUE TITLE
Relationships contain full IRIs, try to encode it to a CURIE

### ISSUE THREAD

**Issue by jnguyenx** [SciGraph/SciGraph#152]
Now that fragments are removed (for #118) relationship names are complete IRIs. Would be nice to also abbreviate these to CURIEs when possible.

**Comment by atorr** [comment]
Hello.  I went ahead and pushed some code for this issue.  Take a look and see if it's what you guys are looking for.

**Comment by jnguyenx** [comment]
Hi @atorr,

That's not the fix I had in mind: since we're creating a TinkerGraph before pushing data to the client, it makes more sense to add the resolution in the TinkerGraphUtil class. However this class is static and needs to have the object curieUtil passed in.

One way to get around that is to change the methods signature, or convert the class to a non-static one. I personally prefer the latter.

**Comment by atorr** [comment]
Hi @jnguyenx,

Yeah, it took me a while to figure out that wasn't the required fix heh, but I was able to find the location of the needed fix.  As a temporary solution I provided an overloaded method for addEdge that allows the option of passing in the curieUtil.  I can also look into converting TinkerGraphUtil into a non-static class.
