### ISSUE TITLE
Release 1.4 coming soon?

### ISSUE THREAD

**Issue by cathzwah** [SciGraph/SciGraph#154]
Dear Chris,

For the Neuroinformatic platform of Human Brain Project, we are using SciGraph as ontology service. We have to rebuild the Graph regularly since our ontologies are modified frequently. Currently we have an automated procedure that run periodically to detect changes both in SciGraph and our ontology repos then the script rebuilds the application and database as needed. 

Ideally we would like to have a specific release of SciGraph in production, however there were a number of issues with Release 1.3 and we decided to use the *master* branch instead for the time being. However as SciGraph is evolving constantly and the API might change unexpectedly, we would like to have the possibility to deploy a specific version of SciGraph and not follow the master branch.

Are you planning to have a major release soon? If not would it be possible for you to create a Release branch 1.4 or a specific tag so that we have a stable version of the application?

Thanks!
Best
Catherine Zwahlen

**Comment by ccondit** [comment]
Please use: https://github.com/SciGraph/SciGraph/tree/Release-1.4
There should be no breaking API changes introduced in that branch.
1.5 will have some changes in API representation and changes package names.

**Comment by cathzwah** [comment]
Thanks Chris for creating release branch so quickly!
