### ISSUE TITLE
Error when loading ontologies with Release-1.4

### ISSUE THREAD

**Issue by cathzwah** [SciGraph/SciGraph#155]
Dear Chris,
when running the command to upload the ontologies with the class `edu.sdsc.scigraph.owlapi.loader.BatchOwlLoader`, I get the exception below.
It seems that there is some dependencies on the next version with the new packages.
Best
Catherine
 
```
Error in custom provider, java.lang.RuntimeException: java.lang.ClassNotFoundException: io.scigraph.neo4j.BatchEdge
  at edu.sdsc.scigraph.neo4j.Neo4jModule.getMaker(Neo4jModule.java:99)
  at edu.sdsc.scigraph.neo4j.Neo4jModule.getMaker(Neo4jModule.java:99)
  while locating org.mapdb.DB
    for parameter 0 at edu.sdsc.scigraph.neo4j.IdMap.<init>(IdMap.java:43)
  while locating edu.sdsc.scigraph.neo4j.IdMap
  at edu.sdsc.scigraph.neo4j.Neo4jModule.configure(Neo4jModule.java:67)
  while locating java.util.concurrent.ConcurrentMap<java.lang.String, java.lang.Long>
    for parameter 4 at edu.sdsc.scigraph.neo4j.GraphBatchImpl.<init>(GraphBatchImpl.java:83)
  while locating edu.sdsc.scigraph.neo4j.GraphBatchImpl
  at edu.sdsc.scigraph.owlapi.loader.OwlLoaderModule.configure(OwlLoaderModule.java:70)
  while locating edu.sdsc.scigraph.neo4j.Graph
    for field at edu.sdsc.scigraph.owlapi.loader.BatchOwlLoader.graph(BatchOwlLoader.java:65)
  while locating edu.sdsc.scigraph.owlapi.loader.BatchOwlLoader
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: io.scigraph.neo4j.BatchEdge
```

**Comment by tgbugs** [comment]
Hi Catherine,
   The issue is that the file directory structure has been renamed so when you run the batch loader the maven call is now
```mvn exec:java -Dexec.mainClass="io.scigraph.owlapi.loader.BatchOwlLoader" -Dexec.args="-c ../devGraph.yaml"```
instead of
```mvn exec:java -Dexec.mainClass="edu.sdsc.scigraph.owlapi.loader.BatchOwlLoader" -Dexec.args="-c ../devGraph.yaml"```

**Comment by ccondit** [comment]
Did you build a graph with `master` which your YAML file is still referencing? I'm betting the mapdb instance was built with master but then referenced with Release-1.4. Try deleting the graph directory and reloading.

**Comment by cathzwah** [comment]
It solved the problem. Thanks
