### ISSUE TITLE
Fix issues with SciGraph for ID type determinations

### ISSUE THREAD

**Issue by jmcmurry** [SciGraph/SciGraph#162]
jmcmurry commented
>
It would be good for me to know if there is an architectural reason that the URLs include the words gene, disease, etc. Does this help with performance or is it just a contextual indication to the human user? I ask because my general preference would be pages that look like monarchinitiative.org/OMIM:PS605552.
>
If we have bare bones URLs then a separate resolver wouldn't be necessary to maintain it. It could (?) also simplify the logic internal to our app.
 @kshefchek
+1
>  

kshefchek commented
>There are still some issues with relying on SciGraph categories to determine ID type, for example, OMIM:PS605552 above and we do not have a specific model type. But once this method becomes reliable we could make the switch.
 @nlwashington
+1
>
   
nlwashington commented
>
I totally get you; I wish we could have a simple url as the one you suggest, so users don't have to know what kind of thing they wish to go to.
>
It doesn't seem like it would add that much overhead to first try to figure out what the thing is by contacting geoffrey, and if it doesn't find it then duckworth, and still if it doesn't find it, then a general search? Maybe kent, could you test this out on a branch with some timing benchmarks? Or perhaps this should be it's own ticket? I think it's worth exploring.
 @kshefchek
+1
>
   
kshefchek commented
>
This is essentially what we're doing with the resolver, but we just head straight to the data scigraph instead of first looking at the ontology graph, so this should be easy to implement. If we do something like this it would be nice to design a web crawler similar to tanuki to iterate over the golr driven tables to see if all of our links resolve.

- [ ] Fix issues with ID type determination in SciGraph
- [ ] Benchmark for performance
- [ ] Design a web crawler similar to tanuki to iterate over the golr driven tables to see if all of our links resolve

**Comment by kshefchek** [comment]
This shouldn't require any updates to SciGraph;

Fix issues with ID type determination in SciGraph - see https://github.com/monarch-initiative/dipper/issues/221
Benchmark for performance - This should not affect performance as we already call SciGraph for basic information such as label, uri, so we coud get all this information in one call.  Even if we make the call redundantly it should be reasonably fast (see the current resolver route as an example)
Design a web crawler -  See https://github.com/kltm/tanuki/issues/1, but we may also want to investigate other options

**Comment by mellybelly** [comment]
Probably need a different ticket(s), but there are two outcomes that are needed related to this: 1) send OMIM IDs to OMIM asap so that we show up on pages like this: http://omim.org/help/external and on individual disease and gene pages in OMIM; 2) develop generic documentation for how third parties can most easily link to us. Then perform outreach to this effect.

(former related to prior closed ticket https://github.com/monarch-initiative/impact/issues/21)

**Comment by kshefchek** [comment]
@mellybelly added a ticket here: https://github.com/monarch-initiative/impact/issues/39

Closing as the info in this ticket is out of scope for scigraph.  The majority of this ticket is captured here: monarch-initiative/dipper#221, for the rest see https://github.com/SciGraph/SciGraph/issues/162#issuecomment-152612361
