### ISSUE TITLE
Give Julie Permission to edit labels for SciGraph tickets please

### ISSUE THREAD

**Issue by jmcmurry** [SciGraph/SciGraph#163]
@nlwashington @kshefchek  The label options are greyed out for me. Is this due to a permissions issue?

![screen shot 2015-10-30 at 09 40 46](https://cloud.githubusercontent.com/assets/3658863/10851814/67dafc70-7eea-11e5-9000-db9bb000f17d.png)

**Comment by cmungall** [comment]
invited you to the dev team

**Comment by jmcmurry** [comment]
@cmungall I didn't get an invite? https://github.com/SciGraph/SciGraph/network/members

**Comment by cmungall** [comment]
Oops.

Invite to random guy canceled. New invite sent out

**Comment by jmcmurry** [comment]
Thanks :)
