### ISSUE TITLE
Add cypher service to run an arbitrary query

### ISSUE THREAD

**Issue by jnguyenx** [SciGraph/SciGraph#174]
Will be useful to test out queries and complementary to the resolve cypher service.

Make sure that the queries can't alter the graph.

**Comment by cmungall** [comment]
And this will include our own extensions - e.g. CURIE and subProperty expansion?

**Comment by jnguyenx** [comment]
Yes that is the main purpose of this new service.

**Comment by jnguyenx** [comment]
https://scigraph-data-dev.monarchinitiative.org/scigraph/docs/#!/cypher/execute

There's a 5 minutes timeout to prevent from killer queries to stall SciGraph.
