### ISSUE TITLE
Execute service should return a json

### ISSUE THREAD

**Issue by jnguyenx** [SciGraph/SciGraph#178]

**Comment by jnguyenx** [comment]
The Neo4j java API does not provide all the info that the shell does. By converting to JSON we lose a bit of information, especially when the query returns a PATH. (e.g. node label, edge type, etc..).

To combine the best of the two worlds, the execute service can either return a JSON with lossy information:
`https://scigraph-data-dev.monarchinitiative.org/scigraph/cypher/execute.json?cypherQuery=START+n+%3D+node%3Anode_auto_index%28iri%3D%27DOID%3A4%27%29+match+%28n%29+return+n&limit=10`

Or the full shell-like output:
`https://scigraph-data-dev.monarchinitiative.org/scigraph/cypher/execute?cypherQuery=START+n+%3D+node%3Anode_auto_index%28iri%3D%27DOID%3A4%27%29+match+%28n%29+return+n&limit=10`

**Comment by cmungall** [comment]
can you give an example with something missing - seems mad that the java API is incomplete

**Comment by jnguyenx** [comment]
I struggled with [PATHs](http://neo4j.com/docs/2.2.8/javadocs/org/neo4j/graphdb/Path.html).

I was using .iterator() instead of .nodes() and .relationships(), so now I managed to fiddle in the missing data!
