### ISSUE TITLE
equivalentClass/subClassOf issues

### ISSUE THREAD

**Issue by tgbugs** [SciGraph/SciGraph#180]
We have encountered unexpected behavior when dealing with some of our old defined classes.

In the definition of NIFNEURNT:nlx_neuron_nt_090803 [here](https://github.com/SciCrunch/NIF-Ontology/blob/master/ttl/NIF-Neuron-NT-Bridge.ttl#L904) the equivalence statement is sufficient in Protege for  NIFNEURNT:nlx_neuron_nt_090803 to be inferred as subClassOf NIFCELL:sao1417703748. However when looking at the [scigraph output](http://matrix.neuinfo.org:9000/scigraph/graph/neighbors/NIFNEURNT:nlx_neuron_nt_090803?depth=2&blankNodes=false&direction=BOTH&project=*) for a neighbors query with depth of 2 this relation does not appear. Running the query with relationshipType=equivalentClass set returns nothing (I think this is expected behavior?)

This seems to be related to https://github.com/SciGraph/SciGraph/issues/135 and https://github.com/SciGraph/SciGraph/issues/42 but I'm not entirely sure if it is the same issue.

**Comment by cmungall** [comment]
Looks like #135 is the more relevant ticket

What's your configuration - are you using a reasoner?

**Comment by tgbugs** [comment]
Reasoner is off (havn't gotten nifstd into reasonable state yet). Configuration is essentially as seen here: https://github.com/SciCrunch/NIF-Ontology/blob/master/scigraph/make_yamls.sh

**Comment by cmungall** [comment]
In that case, this is expected (if undocumented) behavior.

Although in principle we could implement a reasonerless relaxation step, 
that is better kept as the preserve of ontology processing and release 
tools upstream of scigraph, e.g. robot:
https://github.com/ontodev/robot/issues/7

Even if the ontology is messy, I'd recommend using Elk as part of the SG 
load. You can configure SG to drop the disjointness axioms and 
domain/range constraints (which will eliminate issues if you have messy 
object properties or object property usage). Unless you have really 
heinous equivalence axioms, the results should be trustable.

**Comment by jnguyenx** [comment]
Additional note: It should not be related to https://github.com/SciGraph/SciGraph/issues/135 as it is only activated when [this configuration type](https://github.com/monarch-initiative/SciGraph-docker-monarch-data/blob/master/src/main/resources/monarchLoadConfiguration.yaml.tmpl#L125) is specified.

**Comment by tgbugs** [comment]
Adding the reasoner results in the following warning
`WARNING: Not reasoning on Ontology(OntologyID(OntologyIRI(<http://ontology.neuinfo.org/NIF/ttl/nif.ttl>))) [Axioms: 0 Logical Axioms: 0] because it is inconsistent.` so I will indeed need to clean up NIFSTD wrt reasonability before I can resolve this. If the issues persists after the reasoner can run I will reopen. Closing for now.

**Comment by cmungall** [comment]
There's an option to remove disjointness and domain/range axioms prior to loading. These are usually the cause, and they don't really buy you much at the SciGraph level

**Comment by tgbugs** [comment]
Do you happen to have the reference for that option on hand, or know where I can look? (I checked the Elk documentation but nothing jumped out at me).

**Comment by jnguyenx** [comment]
That's should be it:
https://github.com/monarch-initiative/SciGraph-docker-monarch-data/blob/master/src/main/resources/monarchLoadConfiguration.yaml.tmpl#L19
