### ISSUE TITLE
Cannot load sources from https

### ISSUE THREAD

**Issue by jnguyenx** [SciGraph/SciGraph#182]

**Comment by cmungall** [comment]
Are you using an up to date owlapi?

This was a previous problem but now fixed, search the owlapi tracker for deets

**Comment by jnguyenx** [comment]
Indeed we're behind:
net.sourceforge.owlapi:owlapi-distribution ............ 3.5.1 -> 5.0.2

I'll check that in details later on.

Thanks!

**Comment by cmungall** [comment]
5.x may be a big leap. @hdietze @jamesaoverton and I are only now 
switching to 4x. @balhoff what do you use

**Comment by balhoff** [comment]
Just barely starting switch to 4.x.

**Comment by jnguyenx** [comment]
I think that it was a JVM certificate issue, now it loads fine with
```
$ java -version
java version "1.8.0_121"
```
