### ISSUE TITLE
Request for labels on edges

### ISSUE THREAD

**Issue by mbrush** [SciGraph/SciGraph#188]
Not critical, but it would be nice to be able to return the rdfs labels of edges in cypher queries. For example, to return the label 'in taxon' for the object property http://purl.obolibrary.org/obo/RO_0002162 by using "RETURN property.label".  At present, all i can return for an edge such as this is its IRI.

As I said, this is just a convenience so I can see the name of the edges when I am querying or QAing the data in SciGraph.  If it eats up too much space or is otherwise problematic to add these, I am getting by ok without them.

Thanks @jnguyenx

**Comment by jnguyenx** [comment]
@mbrush I did some tests and it's totally feasible to add those in the graph.

Just one question, for owl edges such as subClassOf, subPropertyOf, etc.. they don't have labels but we can use their types as label. Does it make sense that way? For example in the graph we would have:
`:isDefinedBy[14288]{label:"isDefinedBy"}`

**Comment by mbrush** [comment]
I think that  is fine, but can you clarify what you mean by the 'type' of the property?  My scigraph/cypher is rusty and I don't follow what the 'type' is in your example above.

Also, I suspect that most properties/edges that don't have an rdfs:label in our ontologies will have a non-numeric IRI that will tell me what the property means without having to look it up.  (e.g. rdfs:subClassOf is the IRI of this edge/property).

**Comment by jnguyenx** [comment]
https://github.com/SciGraph/SciGraph/wiki/Post-processors#edge-labeler

Labels will be available in the next SciGraph monarch load.
