### ISSUE TITLE
Add a route that implements simple traversals

### ISSUE THREAD

**Issue by cmungall** [SciGraph/SciGraph#201]
`/graph/reachable_from/{id}`

arguments: list of OPs, interpreted as a chain (required)

alternatively, make this optional, but have some kind of bound checking to stop killer queries

Would make this code simpler:

https://github.com/monarch-initiative/biolink-api/blob/d35110b8a6193cfa924e22e8c13c4cd4c5aa6135/scigraph/scigraph_util.py#L159-L161

logic here:

https://github.com/monarch-initiative/biolink-api/blob/d35110b8a6193cfa924e22e8c13c4cd4c5aa6135/scigraph/scigraph_util.py#L81-L114

**Comment by cmungall** [comment]
We also need a route that allows a union of properties to be specified.

So perhaps 3 routes:

 1. one for chain of atomic properties (with global option to include inferred subproperties)
 2. one for union of atomic properties
 3. one for arbitrary scigraph cypher expressions

3 would subsume 1 and 2, but 1 and 2 would be useful in provide a simple interface where the argument is a list or chain of atomic properties.

For 3, the input would be an expression in scigraph-cypher syntax, e.g. `(p1|p2*|!p3+|...)`...

**Comment by jnguyenx** [comment]
Note that I dropped Java 7 support. We'll have to make the move anyway for https://github.com/SciGraph/SciGraph/issues/220.

**Comment by jnguyenx** [comment]
@cmungall can you give it a try? I went with 3 first, and we'll see if we need 1 and 2.

https://scigraph-data-dev.monarchinitiative.org/scigraph/docs/#!/graph/reachableFrom
Don't use the form if you enter multiple arguments, there's a problem with swagger. Issue tracked here: https://github.com/SciGraph/SciGraph/issues/206
