### ISSUE TITLE
/graph/neighbors/ should have option to include inferences over SubPropertyOf

### ISSUE THREAD

**Issue by cmungall** [SciGraph/SciGraph#202]
i.e. the equivalent of `:REL!` in SciGraph-Cypher

Test query. This is empty:

https://scigraph-ontology.monarchinitiative.org/scigraph/graph/neighbors/GO:0000035?depth=1&blankNodes=false&relationshipType=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0000057&direction=BOTH&project=%2A

It should find the edges involving the more specific http://purl.obolibrary.org/obo/RO_0002233

**Comment by tgbugs** [comment]
We are building a hierarchy of phenotype predicates ([here](https://github.com/SciCrunch/NIF-Ontology/blob/neurons/ttl/NIF-Neuron-Phenotype.ttl#L42)) for handling neuron types and this would make it much easier to extract all the phenotypes associated with a neuron. I will add a test query when we have one.

**Comment by dosumis** [comment]
Inferences over subproperties in SciGraph would certainly be useful.

> We are building a hierarchy of phenotype predicates (here) for handling neuron types 

Some of these seem very close to the [Relations we defined in RO](https://academic.oup.com/bioinformatics/article-abstract/28/9/1262/311581/A-strategy-for-building-neuroanatomy-ontologies?redirectedFrom=fulltext)), used in VFB.  Would be good to integrate them.

**Comment by cmungall** [comment]
EquivalentProperty axiom bridge would be great (also if you want to use the RO URIs directly and want to jointly curate we can explore this)

**Comment by tgbugs** [comment]
I have been putting those together based on our narrower use cases with the intention of later going through and mapping/replacing them with existing RO identifiers where appropriate, so when that comes time, definitely interested and will ping back.

**Comment by cmungall** [comment]
Fanstastic! Thanks Tom!

**Comment by jnguyenx** [comment]
I added the same syntax as used in SciGraph-cypher, the ! sign.
https://scigraph-ontology-dev.monarchinitiative.org/scigraph/graph/neighbors/GO:0000035?depth=1&blankNodes=false&relationshipType=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0000057!&direction=BOTH&project=%2A

For some reason the edge type was only accepting IRIs, now it accepts also CURIEs.
https://scigraph-ontology-dev.monarchinitiative.org/scigraph/graph/neighbors/GO:0000035?depth=1&blankNodes=false&relationshipType=RO:0000057!&direction=BOTH&project=%2A

**Comment by cmungall** [comment]
I think it's cleaner to have this as a separate boolean property?

**Comment by jnguyenx** [comment]
Done!

https://scigraph-ontology-dev.monarchinitiative.org/scigraph/graph/neighbors/GO:0000035?depth=1&blankNodes=false&relationshipType=RO:0000057&direction=BOTH&project=%2A
