### ISSUE TITLE
Allow full iris to be labelled as anonymous in neo4j as a configuration

### ISSUE THREAD

**Issue by kshefchek** [SciGraph/SciGraph#209]
Some users may use full iri's to represent blank/anonymous nodes, see
https://www.w3.org/TR/rdf11-concepts/#section-skolemization

For example a base iri representing a bnode could be:
http://example.com/.well-known/genid/{id}

Could we make this configurable for scigraph?

**Comment by jnguyenx** [comment]
https://github.com/SciGraph/SciGraph/wiki/Post-processors#anonymous-node-tagger
