### ISSUE TITLE
dynamic/shortest 500

### ISSUE THREAD

**Issue by goodb** [SciGraph/SciGraph#229]
request
https://scigraph-data.monarchinitiative.org/scigraph/dynamic/shortest?start_id=HP%3A0011014&end_id=HP%3A0000118&max_depth=1

response
{
  "code": 500,
  "message": "There was an error processing your request. It has been logged (ID e97fa0aef407dbfa)."
}

**Comment by kshefchek** [comment]
Duplicate here: https://github.com/SciGraph/SciGraph/issues/242 - this was first but closing since the other has more information.
