### ISSUE TITLE
Miscategorizing and new edges to owl:Nothing

### ISSUE THREAD

**Issue by kshefchek** [SciGraph/SciGraph#236]
In our last SciGraph load I noticed that owl:Nothing is a direct subClass of all leaf nodes in our ontologies, meaning it also gets labelled with every category in our configuration, for example:

https://scigraph-ontology-dev.monarchinitiative.org/scigraph/graph/neighbors/HP%3A0002527?depth=1&relationshipType=subClassOf&direction=INCOMING

If this is logically correct we can work around it, but it's odd that this wasn't present in our last release: 
https://scigraph-ontology.monarchinitiative.org/scigraph/graph/neighbors/HP%3A0002527?depth=1&blankNodes=false&relationshipType=subClassOf&direction=INCOMING&entail=false

**Comment by cmungall** [comment]
For a full explanation see 

https://github.com/geneontology/amigo/issues/428

**Comment by kshefchek** [comment]
Okay great, I'll fix when generating monarch.owl level will owltools.

**Comment by cmungall** [comment]
I think the fix may have to be at the scigraph level.

If the ontology has unsatisfiable classes, the materialization of owl:Nothing may be hard to avoid (of course, we should have better ontology QC but this is hard, multiple async releases).

If there are no unsats then there should be no classes that explicitly reference Nothing, so it may not surface at the API level, but I'm not sure this is precisely defined at the OWLAPI level.

The safest thing is just to have the scigraph loader always ignore Nothings

**Comment by kshefchek** [comment]
I believe this is happening when performing EL reasoning, since I can't find these in monarch-merged.owl.  We could add a setting at the reasoning step, this seems like a hack but a little less hacky then checking every axiom at load time.  For example:

reasonerConfiguration:
      factory: org.semanticweb.elk.owlapi.ElkReasonerFactory
      addDirectInferredEdges: true
      addInferredEquivalences: true
      removeUnsatisfiableClasses: true
      removeClasses:
          - http://www.w3.org/2002/07/owl#Nothing

Interesting that we have 'removeUnsatisfiableClasses' set to true, but these still show up.  Maybe something has changed at the elk api level?

**Comment by kshefchek** [comment]
@cmungall would you be able to create a small ontology that would allow me to test this?  For example:
https://github.com/SciGraph/SciGraph/blob/master/SciGraph-core/src/test/resources/ontologies/unsat.owl

**Comment by cmungall** [comment]
> Interesting that we have 'removeUnsatisfiableClasses' set to true, but these still show up

it's possible for unsats to be removed and for Nothing to remain. It's a builtin like Thing.

If you ask the reasoner API for all subclasses of a satisfiable class it should return Nothing to be complete. I think in some circumstance it won't as Nothing won't be an entity that has been declared, but the moment you have unsats suddently Nothing is 'exposed'? I'd have to check. Either way we need to be defensive.

**Comment by cmungall** [comment]
```
Prefix: owl: <http://www.w3.org/2002/07/owl#>
Prefix: rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
Prefix: rdfs: <http://www.w3.org/2000/01/rdf-schema#>
Prefix: xml: <http://www.w3.org/XML/1998/namespace>
Prefix: xsd: <http://www.w3.org/2001/XMLSchema#>
Prefix: : <http://example.org/>

## Test
Ontology: <http://example.org/test>

Class: :A

Class: :B SubClassOf: :A

Class: :C SubClassOf: :A

Class: owl:Nothing SubClassOf: :C
```

**Comment by kshefchek** [comment]
Thanks! These are no longer in appearing in the latest load so it may be harder to track down.  It's likely when I was debugging monarch.owl it had already resolved.

**Comment by kshefchek** [comment]
Replacing with https://github.com/ontodev/robot/issues/173

**Comment by kshefchek** [comment]
Ended up deleting these directly with cypher:

    MATCH ()-[r]-(nothing:Node{iri:'http://www.w3.org/2002/07/owl#Nothing'}) DELETE r;
    MATCH (nothing:Node{iri:'http://www.w3.org/2002/07/owl#Nothing'}) DELETE nothing;
