### ISSUE TITLE
services graph/neighbors fails when curie used for relationshipType

### ISSUE THREAD

**Issue by tgbugs** [SciGraph/SciGraph#241]
Using the curied form of the IRI for the relationshipType does not work and an error is returned.
Examples: `UBERON:0000955` with `BFO:0000050` [fails](http://trinity.neuinfo.org:9000/scigraph/graph/neighbors/UBERON:0000955?depth=1&blankNodes=False&relationshipType=BFO%3A0000050&direction=BOTH&project=%2A) the curie for the relationship is present [here](http://trinity.neuinfo.org:9000/scigraph/vocabulary/id/BFO:0000050), and running the query using the expanded iri works as expected [here](http://trinity.neuinfo.org:9000/scigraph/graph/neighbors/UBERON:0000955?depth=1&blankNodes=False&relationshipType=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000050&direction=BOTH&project=%2A). The example is running on 3e1c0e1ae9bc84ddf11c38d68d1e5bc850cfb9b4, but the issues is still present at 46049b93b3df8c5e8b9756125af99da85c44c078.

**Comment by cmungall** [comment]
This is odd we use these all the time...

**Comment by kshefchek** [comment]
This works on our latest build, but it would interesting to track down why this is failing.  Is there anything of interest in the logs?

https://scigraph-data-dev.monarchinitiative.org/scigraph/graph/neighbors/UBERON:0000955?depth=1&blankNodes=False&relationshipType=BFO%3A0000050&direction=BOTH&project=*

**Comment by tgbugs** [comment]
I retested this morning on the latest version, and it is definitely working as expected. Some wires must have gotten crossed somewhere in my test code since I was working with 4 different scigraph instances (I think due to a curie that I have in one place but not in another). Closing as fixed. Sorry for the confusion.
