### ISSUE TITLE
dynamic/shortest   code: 500

### ISSUE THREAD

**Issue by NuriaQueralt** [SciGraph/SciGraph#242]
Hi, i am trying this api call with the parameters values suggested in the documentation of the endpoint:

https://scigraph-data.monarchinitiative.org/scigraph/dynamic/shortest?start_id=HP%3A0011014&end_id=HP%3A0000118&max_depth=4

response:
{
"code":500,
"message":"There was an error processing your request. It has been logged (ID 39783e8f4fc0c835)."
}

I am doing something wrong? 
Many thanks in advance,
Núria

**Comment by kshefchek** [comment]
This depends on fixing https://github.com/monarch-initiative/monarch-cypher-queries/issues/17 and https://github.com/SciGraph/SciGraph/issues/243

**Comment by kshefchek** [comment]
@NuriaQueralt thanks for reporting!  This is an issue with the monarch specific configuration using cypher syntax that was deprecated in Neo4J 3

As a work around, you can use the cypher execution service.  The only downside is that you will have to query on full IRIs for nodes.  For example:

    MATCH path = shortestPath((start:Node{iri:'http://purl.obolibrary.org/obo/HP_0100750'})-[:subClassOf|equivalentClass*..4]->(end:Node{iri:'http://purl.obolibrary.org/obo/MP_0005388'}))
    RETURN path

The service is located here:
https://scigraph-data.monarchinitiative.org/scigraph/cypher/execute.json
params:
cypherQuery: MATCH (foo) RETURN foo
limit: 10

For example:
https://scigraph-data.monarchinitiative.org/scigraph/cypher/execute.json?cypherQuery=MATCH%20path%20%3D%20shortestPath((start%3ANode%7Biri%3A%27http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0100750%27%7D)-%5B%3AsubClassOf%7CequivalentClass*..4%5D-%3E(end%3ANode%7Biri%3A%27http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMP_0005388%27%7D))%20RETURN%20path&limit=10

**Comment by NuriaQueralt** [comment]
@kshefchek Thanks for your prompt reply! your alternative suggestion has worked perfectly! i have retrieved the full IRIs (the only 'tricky' thing let's say..) using the /cypher/execute endpoint and the
`query=START n=node:node_auto_index(iri='CHEBI:506227') match (n) return n` because the /cypher/curies endpoint that seemed to me the way to go, did not work though..

**Comment by kshefchek** [comment]
This is fixed on ontology-dev and data-dev, for example https://scigraph-data-dev.monarchinitiative.org/scigraph/dynamic/shortest.json?start_id=HP%3A0011014&end_id=HP%3A0000118&max_depth=4
