### ISSUE TITLE
Install SciGraph-core as a dependency

### ISSUE THREAD

**Issue by Zigur** [SciGraph/SciGraph#245]
Hello, I would like to use SciGraph to load ontologies  (in OWL format) on a Neo4J database. Now if I want to use it programmatically in a Java project built with Gradle (or Maven), how can I import the dependency? It doesn't seem to live on MVN central. Should I build it locally and install it manually? I haven't been using Java in while, so I am a bit rusty, honestly.

**Comment by tgbugs** [comment]
The is some info in the readme on building, I have some documentation of the config files [here](https://github.com/SciCrunch/NIF-Ontology/blob/master/scigraph/make_yamls.sh) as well.
I also have a slightly more detailed setup in the readme [here](https://github.com/SciCrunch/SciGraph/blob/example/README.md).
From the README:

Build the graph:

cd SciGraph-core
mvn exec:java -Dexec.mainClass="io.scigraph.owlapi.loader.BatchOwlLoader" -Dexec.args="-c src/test/resources/pizzaExample.yaml"

Run the services:

cd ../SciGraph-services
mvn exec:java -Dexec.mainClass="io.scigraph.services.MainApplication" -Dexec.args="server src/test/resources/pizzaConfiguration.yaml"

**Comment by kshefchek** [comment]
Also see https://github.com/SciGraph/SciGraph/issues/192

**Comment by kshefchek** [comment]
@Zigur we are stalled on adding scigraph to maven central since another organization has claimed scigraph.org and scigraph.io.  I'll mark this as a duplicate to #192.  Unfortunately for the time being you will have to build locally to use SciGraph as a dependency.

**Comment by Zigur** [comment]
@kshefchek Thanks for the clarification!
