### ISSUE TITLE
Add a route to get prefix map

### ISSUE THREAD

**Issue by cmungall** [SciGraph/SciGraph#261]
We have /prefixes, which returns just the prefixes, but we need a way to get the prefix->uribase map

**Comment by kshefchek** [comment]
I believe we already have what you are describing in cypher/curies, eg:
https://scigraph-data.monarchinitiative.org/scigraph/cypher/curies

or am I misunderstanding?

**Comment by cmungall** [comment]
ah missed that.

Slightly odd route name as it doesn't return curies, but probably too disruptive to change now
