### ISSUE TITLE
vocabulary query with category= fails

### ISSUE THREAD

**Issue by tgbugs** [SciGraph/SciGraph#263]
I have encountered strange behavior where category restriction queries do not work.
My development server built against 23b4176 lists the categories https://scigraph.olympiangods.org/scigraph/vocabulary/categories but when I try to run queries with them I get 404 errors.
1. 200 https://scigraph.olympiangods.org/scigraph/vocabulary/term/brain
2. 404 https://scigraph.olympiangods.org/scigraph/vocabulary/term/brain?category=anatomical%20entity
3. 404 `https://scigraph.olympiangods.org/scigraph/vocabulary/term/brain?category="anatomical entity"`
4. 404 `https://scigraph.olympiangods.org/scigraph/vocabulary/term/brain?category="anatomical%20entity"`

I cannot test against autocomplete or search because I get 500 errors (covered in another issue).

This issue also appears on SciCrunch production built from https://github.com/SciCrunch/SciGraph/tree/upstream.

**Comment by kshefchek** [comment]
Category filters work for the monarch instance, maybe it's the double quotes?  https://scigraph-ontology.monarchinitiative.org/scigraph/vocabulary/term/brain?limit=20&searchSynonyms=true&searchAbbreviations=false&searchAcronyms=false&category=anatomical%20entity

**Comment by tgbugs** [comment]
The quotes don't seem to be the issue (though they are an issue as seen by querying the monarch endpoint). https://scigraph.olympiangods.org/scigraph/vocabulary/term/brain?limit=20&searchSynonyms=true&searchAbbreviations=false&searchAcronyms=false&category=anatomical%20entity shows up in the logs as `"GET /scigraph/vocabulary/term/brain?limit=20&searchSynonyms=true&searchAbbreviations=false&searchAcronyms=false&category=anatomical%20entity HTTP/1.1" 404` some something is still wrong.

Comparing https://github.com/monarch-initiative/SciGraph-docker-monarch-data/blob/master/src/main/resources/monarchLoadConfiguration.yaml.tmpl and https://github.com/tgbugs/pyontutils/blob/master/scigraph/graphload.yaml.template doesn't reveal any obvious issues, though I do run that template through python yaml and it comes out with categories at the top, however it is clear that categories are in Neo4j since they can be seen in the results for queries e.g. here https://scigraph.olympiangods.org/scigraph/vocabulary/term/synganglion. I'm going to strip down our services.yaml to see whether it makes a difference.

**Comment by tgbugs** [comment]
Stripping down services.yaml doesn't seem to have done anything.
These lines are also present in the build output. So extra confirmation that they are in the graph.
```
INFO: Tagging 10262 for disease
INFO: Tagging 208 for organism
INFO: Tagging 5123 for subcellular entity
INFO: Tagging 20665 for anatomical entity
INFO: Tagging 12947 for Resource
INFO: Tagging 40955 for biological process
INFO: Tagging 364 for Institution
INFO: Tagging 508 for cell
INFO: Tagging 37902 for molecular entity
INFO: Tagging 2092 for quality
```

**Comment by tgbugs** [comment]
Finally figured out what it was. In graphload.yaml `- category` must be included in `indexedNodeProperties` otherwise everything fails. Hopefully this note will help anyone else who might encounter the issue. It might also be worth adding `- category` by default it any categories are set since the desire to have them indexed is probably the default desire. If someone wants the categories but not the ability to filter on them then that should probably be set manually rather than how it works right now.
