### ISSUE TITLE
Need to provide CURIE list for NIFSTD

### ISSUE THREAD

**Issue by twhetzel** [SciGraph/SciGraph#50]
The web service call getCuriePrefixes returns an empty list:
http://matrix.neuinfo.org:9000/scigraph/vocabulary/prefixes?callback=fn
http://matrix.neuinfo.org:9000/scigraph/docs/#!/vocabulary/getCuriePrefixes

**Comment by ccondit** [comment]
The list is empty because NIF hasn't defined any CURIE prefixes (probably because NIF hasn't ever used CURIES). This can be configured by adding appropriate mappings to the application configuration.

**Comment by twhetzel** [comment]
The prefixes were specified and a request to re-load NIFSTD was sent before the break. Let's leave this item open until we can confirm this web service is returning the correct content after re-loading NIFSTD.

**Comment by ccondit** [comment]
Wait - there are two separate issues here. One is the categories and one is the CURIEs. Which is this ticket about?

**Comment by twhetzel** [comment]
Sorry, this ticket is for the "getCuriePrefixes" call. Is this a different mapping/configuration file than what is needed for "getCategories"? If yes, can you point me to details of what is needed for the "getCuriePrefixes" call?

**Comment by ccondit** [comment]
Yes - the CURIEs are separate from the categories. Monarch's CURIE configuration looks something like this:

    curies:
      http://purl.obolibrary.org/obo/DOID_ : DOID
      http://purl.obolibrary.org/obo/ORPHANET_ : ORPHANET
      ...

**Comment by twhetzel** [comment]
Refer to Jira NIF-9399 for discussion about SOLR and format using commas.

**Comment by ccondit** [comment]
How is NIF-9399 related to this ticket?

**Comment by twhetzel** [comment]
I believe Chris M. mentioned ticket NIF-9399 in relation to this one.

**Comment by cmungall** [comment]
Not this one. NIF-9399 is about how lists are modeled in the federation solr views, which may have an impact on how closure indexing is done for views such as the one mentioned on the arch call, I think the resources view.
