### ISSUE TITLE
Fetch subgraph based on descendant query

### ISSUE THREAD

**Issue by cmungall** [SciGraph/SciGraph#54]
Scenario: we would like to visualize areas of SciGraph, such as all
the disease nodes of a certain subtype, and all the phenotypes they
give rise to. For example, for a query of Parkinson's Disease, we
would see a node for each subtype in OMIM, plus their
phenotypes. Currently we view this as a table, but this makes it hard
to see shared phenotypes and relationships between phenotypes.

E.g phenotype tab here:
http://monarchinitiative.org/disease/DOID_14330

The same query pattern can apply to other datatypes; e.g. genes to GO annotations

```
Input: a class D and a relation R (e.g. has-phenotype) and a class A

Return: graph containing edges
  (D' R' A')
  where D' is a reflexive SubClassOf descendant of D
  where A' is a reflexive SubClassOf descendant of A
  where E' is a reflexive SubPropertyOf descendant of R

Add to graph:
  all superclasses of D and A, plus all direct SubClassOf edges connecting them (aka topology graph)
```

Example 1:
- D = Parkinson's disease
- R = has-phenotype
- A = unspecified / owl:Thing

(this would be a likely query for driving a graph display of the phenotype tab on the PD page)

Example 2:
- D = unspecified / owl:Thing
- R = has-phenotype
- A = HP:Tremors

(this would be a likely query for driving a graph display of the disease tab on the Tremor's phenotype page)

@cmungall will help write junit tests

@kshefchek will test by writing visualization in scratch pages (e.g by extending @kltm's cytoscape.js based tool)

**Comment by ccondit** [comment]
Implemented a preliminary version of this using the dynamic cypher queries from #66
@kshefchek Have a look at:
http://rosie.crbs.ucsd.edu:9000/scigraph/dynamic/phenotypes_from_disease.json?disease_id=DOID_0050013
and
http://rosie.crbs.ucsd.edu:9000/scigraph/dynamic/diseases_from_phenotype.json?phenotype_id=HP_0007351

**Comment by kshefchek** [comment]
Will start playing around with the directed graph visualization.  Maybe it is also worth trying out d3 with canvas, which should be pretty similar to what we do with d3 and svg (and keep our viz library consistent).  Will also play around with @kltm's cytoscape.js tool.

**Comment by ccondit** [comment]
@kshefchek, let me know if you need other graph formats. Note that SciGraph can currently produce the BBOP json format, graphml, graphson, and gml. Shouldn't be too much trouble to add others if necessary.

**Comment by kltm** [comment]
@kshefchek that code is a wee bit crusty and may not work anymore. If you have any questions, let me know.

**Comment by harryhoch** [comment]
@kschefchek, at the risk of getting into a religious argument, why bother to mess with canvas? Is there some value-added there that SVG does not provide?


> On Feb 26, 2015, at 6:53 PM, kltm <notifications@github.com> wrote:
> 
> @kshefchek that code is a wee bit crusty and may not work anymore. If you have any questions, let me know.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

----
Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu 		412 648 9300

**Comment by kshefchek** [comment]
I'm happy testing it out with SVG.  I've never used canvas so I have no real comparison.  We can see if there are any performance issues with larger graphs.

**Comment by kltm** [comment]
@kshefchek Generally, unless you're going through a library that provides it (I'm guessing D3 does in this case), a canvas graph would not provide any interactivity, so there'd have to have an extra overlay layer to capture events and map them to something meaningful. While canvas is great for graphics rendering (Doom), it has no associated DOM to work with.

If the engines can be switched trivially, it might be interesting to see how the D3 interaction layer performs (invisible objects mapping) vs DOM.

From our experience, hundreds seemed fine in SVG with minimal events, thousands not so much.

**Comment by kshefchek** [comment]
Do we have an idea of how many nodes we want to visualize at one time?

**Comment by kshefchek** [comment]
@cmungall can this be retired?
