### ISSUE TITLE
Filtering reified association nodes from path queries

### ISSUE THREAD

**Issue by cmungall** [SciGraph/SciGraph#6]
Example. Start here: http://tartini.crbs.ucsd.edu/labs/cy-explore-demo
Type "SHH" and choose concentric

Amongst the links will be gene-gene interactions.

We model these using the pattern

```
A interacts_with B
N type "Association"
N hasSubject A
N hasObject B
N hasProperty interacts_with
N dc:source PMID:nnn
```

i.e. rdf-style reification (but not actual rdf reification - we may want a different vocabulary)

When thinking in graph-oriented terms the reified node should really be hidden. Not clear where this should take place. Neo4j doesn't directly support hypergraphs.

However, Neo4j does allow open ended lists of tag-value properties to edges, so the above could be modeled as a graph

    N = {A,B,PMID:nnn}
    E = { A->B [type:interacts_with, source:PMID:nnn]}

However, the PMID here is not (AFAICT) a true node.

We may also want to model associations directly in scigraph.frames and have specific REST calls for them

**Comment by ccondit** [comment]
I believe these issues have all been resolved with subsequent work.
