### ISSUE TITLE
Bulk query adaptors?

### ISSUE THREAD

**Issue by mellybelly** [SciGraph/SciGraph#67]
Can you all discuss what sort of components would be needed for third party systems like Galaxy, Intermine, etc. to be able to pull data from SciGraph?

Maybe nothing special is needed other than some documentation, but just want to put these particular use cases on your radar.

**Comment by ccondit** [comment]
Is this related to #5. Would the data in question be the entire graph or just a subset of it?

**Comment by mellybelly** [comment]
Hi Chris,
Yes the types of queries are same as #5, but with the exception that someone would query SciGraph via a third party system for some subset of the graph. 

For example, a Galaxy user might want to import all phenotypes on a given chromosome into their Galaxy project.  I'm just wondering if there is anything we might want to do to make it easy to embed a SciGraph query tool in other sites to pull data - so not end users but other platform users.

**Comment by ccondit** [comment]
The currently supported formats are documented here:
https://github.com/SciGraph/SciGraph/wiki/REST-Graph-Formats

It would be easy to add other formats as clients require them. Let's take those as new tickets.
