### ISSUE TITLE
Update external ontology (HBP Use Case)

### ISSUE THREAD

**Issue by cathzwah** [SciGraph/SciGraph#70]
Update externally maintained ontologies. Those should never be edited internally.
#### New ontology available in obo or owl
1. API call to upload the ontology file.
2. Terms are immediately available

#### Update an ontology with a new version in obo or owl
1. Update ontology version and date of load
2. Term not modified -> nothing happen
3. Modified properties of term (eg, modify name, add synonyms). The expected behaviour would be to archive the previous version of the term and update the term with the new values
4. Modify relations between terms. In the ideal situation, it should be possible to retrieve the state of the ontology at any point in the past. Relations should not be deleted but archived if there are removed from the ontology.

**Comment by ccondit** [comment]
@cathzwah I think you may have the wrong project...

**Comment by jgrethe** [comment]
Hi Chris,
Catherine is part of the HBP group that I mentioned a few weeks ago in regards to using SciGraph and the need for services to dynamically add/suggest terms to SciGraph.  She has been reviewing SciGraph and was collecting some HBP use cases for SciGraph.  So I am reopening these.  Will tag these.

**Comment by twhetzel** [comment]
@jgrethe can we set-up a call to discuss these requirements?
