### ISSUE TITLE
Update ontology (HBP Use Case)

### ISSUE THREAD

**Issue by cathzwah** [SciGraph/SciGraph#71]
Add term to a HBP ontology for example to the methods ontology.

#### A scientist add a new term to the method ontology
1. The term is created with a status "need curation". 
2. The term is available for the scientist to annotate data
3. The term is reviewed by a curator and approved or merged with another term.

#### A scientist modifies a term
1. The original term is kept and is still the one that is available to the service
2. The term will be flagged for approval
3. The term is reviewed by a curator

**Comment by jgrethe** [comment]
HBP Use Case

**Comment by cmungall** [comment]
We have a project where we are considering SciGraph as an updateable store. Obviously this is a big piece of work as SG is currently intended as a query/integration engine. It would be useful to compare requirements
