### ISSUE TITLE
Add NCBIGene to curie map

### ISSUE THREAD

**Issue by kshefchek** [SciGraph/SciGraph#86]
It looks like NCBIGene is currently mapped to OBO, for example:
http://geoffrey.crbs.ucsd.edu:9000/scigraph/vocabulary/autocomplete/SHH.json?limit=20&searchSynonyms=true&searchAbbreviations=false&searchAcronyms=false&includeDeprecated=false

The curie map should be:
'NCBIGene' : 'http://www.ncbi.nlm.nih.gov/gene/'

**Comment by ccondit** [comment]
Looks like the CURIE map is correct - the data has the wrong IRI...

**Comment by nlwashington** [comment]
genes are currently being loaded both as part of monarch.owl (from disco2turtle) and the ttl output of the dipper pipeline.  these need to be unified.  the ttl file should replace the file that monarch.owl references.  @cmungall is working on pointing monarch.owl to the new file.
