### ISSUE TITLE
new query for genotype-to-phenotype

### ISSUE THREAD

**Issue by nlwashington** [SciGraph/SciGraph#87]
i want to be able to query from genotype to get the phenotypes (via RO:has_phenotype).

/dynamic/genotypes/:genotype_id/phenotypes/

here, we only want the direct associations between a genotype and phenotype (as opposed to inferring phenotype from the genotype-parts).

for the inverse query:
/dynamic/phenotypes/:phenotype_id/genotypes/

we also only want direct associations between genotypes (GENO:0000000) and phenotypes

**Comment by ccondit** [comment]
Implemented - see:
http://duckworth.crbs.ucsd.edu:9000/scigraph/dynamic/genotypes/MGI:2663179/phenotypes
and
http://duckworth.crbs.ucsd.edu:9000/scigraph/dynamic/phenotypes/MP:0000540/genotypes
