### ISSUE TITLE
NCBIGenes have prefix OBO:NCBIGene_ for curies

### ISSUE THREAD

**Issue by kshefchek** [SciGraph/SciGraph#92]
I believe there was an issue with yaml configuration, would it be possible to correct this and reload?

**Comment by ccondit** [comment]
Is this on geoffrey? Update the configuration here:
https://github.com/monarch-initiative/dipper/blob/master/dipper/curie_map.yaml
and I can redeploy the application.

**Comment by kshefchek** [comment]
That looks right, maybe this is an upstream issue with the ontology import?

**Comment by ccondit** [comment]
What's the resource that's having the trouble?

**Comment by kshefchek** [comment]
On geoffrey all entrez genes are prefixed with OBO, so perhaps the URI from the ontology is actually http://purl.obolibrary.org/obo/ ?  For example:
http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/OBO:NCBIGene_6469

**Comment by nlwashington** [comment]
This us in flux. Thus is the issue if differences between genes in
monarch.owl vs ncbigene.ttl...genes are coming in two places, and we are
working on unifying them. Let's work in this tomorrow.

**Comment by kshefchek** [comment]
bump

**Comment by nlwashington** [comment]
@cmungall, has the monarch.owl import changed to pull from the new ncbigene.ttl on nif-crawler, instead of from our owl disco2turtle dump?

also, should the genes even be in the ontology?  we can have them be part of the vocabulary services without them being loaded into the monarch.owl directly.

**Comment by cmungall** [comment]
Removed genes import from monarch.owl (someone still needs to run the bamboo that generates http://nif-crawler.neuinfo.org/monarch/owl/)

The ttl on nif-crawler is currently the definitive location, the URLs used there are canonical. So yes, add this to vocab services load.

**Comment by kshefchek** [comment]
Looks like this is fixed now.

**Comment by cmungall** [comment]
let's make a behave test and close the ticket!

**Comment by kshefchek** [comment]
This is a semi related test https://github.com/monarch-initiative/monarch-app/commit/d17735fb8927a0058eceb96425d5dd3780178d4e

We could add a more specific test to check the Curie/ID

**Comment by ccondit** [comment]
Go ahead and close if this is resolved to your satisfaction...
