### ISSUE TITLE
sometimes csv output

### ISSUE THREAD

**Issue by nlwashington** [SciGraph/SciGraph#99]
it seems some of the services that return a simple list are amenable to also outputing a csv.  can we consider adding this?

for example:
http://localhost:8080/scigraph/dynamic/genes/NCBIGene:14183/genotypes/targets.json

we get a blob back with an array of nodes like:
nodes": [{
"id": "MGI:3766095",
"lbl": "Fgfr2<tm2.1Lni>/Fgfr2<tm2.1Lni>[involves: 129S1/Sv * 129X1/SvJ * C57BL/6]",
"meta": {
"category": 
["intrinsic genotype"]}}, ...]

this seems like it could easily be flattened into a csv of:
id | lbl | meta  OR
id | lbl | category

seems like some folks might just want the csv without having to deal with parsing the json.

**Comment by ccondit** [comment]
Is the general feature request here to just return a CSV of nodes in a subgraph?
